### ISSUE TITLE
./migrate.py

### ISSUE THREAD

**Issue by premanandmanimaran** [arminfelder/gridfsmigrate#6]
I am trying to move the file upload from GridFS to Amamzon S3. 

When I downloaded the Migrate.py to /home/ubuntu
and Run $ python migrate.py <cmd> 
getting error
bash: syntax error near unexpected token `newline'

Please help

**Comment by arminfelder** [comment]
how did you download the file?, does this also happen, if you clone this repo?

**Comment by premanandmanimaran** [comment]
I downloaded the zip and unzip and moved the migrate.py to /home/ubuntu/
them $ python migrate.py <cmd> 
i get this error
bash: syntax error near unexpected token `newline'

**Comment by premanandmanimaran** [comment]
If run $ ./migrate.py
i permission error
bash: ./migrate.py: Permission denied

**Comment by arminfelder** [comment]
on *nix systems you normally have to set the execute bit manually, by running: chmod +x migrate.py

**Comment by premanandmanimaran** [comment]
Thanks I did chmod +x migrate.py 
am I suppose to get any response cause i didnt get 
root@ip-xxx-xxx-xx-xx:~#  chmod +x migrate.py
root@ip-xxx-xxx-xx-xx:~# ./migrate -c dump -d /app/uploads -r rocketchat -t AmazonS3 -d bucket_name
bash: ./migrate: No such file or directory

**Comment by arminfelder** [comment]
*nix systems follow the philosophy, to only give feedback to the user, in case of an error
also you have to call the application by its full filename:
./migrate.py not ./migrate

**Comment by premanandmanimaran** [comment]
Thanks
 I getting this error
:~# ./migrate.py -c dump -d /app/uploads -r rocketchat -t AmazonS3 -d bucket_name
Traceback (most recent call last):
  File "./migrate.py", line 26, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

Before Running , I changed the File Upload storage type to Amamzon S3 ( added the following fields Bucket Name, acl, Bucket url , Force Path ( set to True) ,Signature Version (v4) URLs Expiration Timespan ( 120), Proxy Avatars ( false), Proxy Uploads (false) )

**Comment by arminfelder** [comment]
pymongo is a dependency which could be installed using pip: pip3 install pymongo

**Comment by premanandmanimaran** [comment]
:$ pip install pymongo
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pymongo
  Downloading https://files.pythonhosted.org/packages/6e/ea/353a9f8ced71b9e258438aa4d6aa048c1eaf5b774d3ef2273d686fde0947/pymongo-3.8.0-cp27-cp27mu-manylinux1_x86_64.whl (410kB)
    100% |████████████████████████████████| 419kB 2.9MB/s
Installing collected packages: pymongo
Successfully installed pymongo-3.8.0
root@ip-xxxxxx:~# ./migrate.py -c dump -d /app/uploads -r rocketchat -t AmazonS3 -d bucket_name
Traceback (most recent call last):
  File "./migrate.py", line 26, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

**Comment by premanandmanimaran** [comment]
@ arminfelder 

Thanks for you reply

Just wanted to check , i trying all this on my Production server. Will this affect the functioning of Rocket chat ?

For me to get the File upload storage to point to Amamzon S3 Server i need to remove data from GridFs . So Amazon S3 works ...otherwise I keep getting Internal Error 500 when i set Storage type : Amamzon S3 .

**Comment by arminfelder** [comment]
the script should not interrupt your operations but it is best practice to make backups!(mongodump), or even go to maintenance mode

**Comment by premanandmanimaran** [comment]
I have done mongodump before starting 
Now i am just trying to find a way to set the storage to Amamzon S3

I used pip instead of pip3 and i got the above error. Anyway to fix this.

**Comment by arminfelder** [comment]
try "sudo chown ubuntu:ubuntu /home/ubuntu -R" to fix ownership of your home folder

**Comment by premanandmanimaran** [comment]
i tried pip3 install pymongo and it passed
Now new error on boto3
root@ip-172-31-14-152:~#  ./migrate.py -c dump -d /app/uploads -r rocketchat -t AmazonS3 -d bucket_name
Traceback (most recent call last):
  File "./migrate.py", line 224, in <module>
    store = AmazonS3Store(obj, args.destination)
  File "./migrate.py", line 54, in __init__
    import boto3
ModuleNotFoundError: No module named 'boto3'

**Comment by premanandmanimaran** [comment]
i tried pip3 install boto3 and it passed
Now when running
root@ip:~# ./migrate.py -c dump -d /app/uploads -r rocketchat -t AmazonS3 -d bucket_name
1. Dumping iMWFJMgrwKXT9Bm7w Audio record.mp3
Traceback (most recent call last):
  File "./migrate.py", line 232, in <module>
    obj.dumpfiles("rocketchat_uploads", store)
  File "./migrate.py", line 117, in dumpfiles
    key = store.put(filename, data, upload)
  File "./migrate.py", line 68, in put
    entry['name']) + '"')
  File "/usr/local/lib/python3.6/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.6/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.6/dist-packages/botocore/signers.py", line 157, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.6/dist-packages/botocore/auth.py", line 425, in add_auth
    super(S3SigV4Auth, self).add_auth(request)
  File "/usr/local/lib/python3.6/dist-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials


My Amazon S3 Settings
Amamzon S3 ( added the following fields Bucket Name, acl, Access Key , Secret Key, Region, Bucket url , Force Path ( set to True) ,Signature Version (v4) URLs Expiration Timespan ( 120), Proxy Avatars ( false), Proxy Uploads (false) )


Am i missing anything.

**Comment by premanandmanimaran** [comment]
@arminfelder 

Hi 

Need your help with this issue. 

Prem

**Comment by arminfelder** [comment]
@premanandmanimaran the Amazon S3 integration was written by @JoyceBabu , but I guess you haven't set the credentials like explained here: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html#configuration
